theme: jekyll-theme-leap-day
title: Result Library API
description: A Java library to handle success and failure without exceptions
current_version: 0.1.1.0
show_downloads: true
logo: https://dev.leakyabstractions.com/result/result-banner.png
